data:
  train: data/coco_trainval35k.json
  valid: data/coco_minival5k.json
#  train: data/coco_sample.json
#  valid: data/coco_sample.json
basenet:
  type: resnet
  arch: resnet50
  pretrained: True
  dilation: False     #DC5 in the paper
  return_interm_layers: False
  lr_backbone: 1e-5
transformer:
  hidden_dims: 256
  position_embedding: sine
  dropout: 0.1
  nheads: 8
  dim_feedforward: 2048
  enc_layers: 6
  dec_layers: 6
  pre_norm: False
detr:
  aux_loss: True
  num_queries: 100
box_matcher:
  cost_class: 1
  cost_bbox: 5
  cost_giou: 2
loss:
  bbox_loss_coef: 5
  giou_loss_coef: 2
  eos_coef: 0.1
params:
  batch_size: 7
  optimizer: AdamW
  lr: 1e-4
  weight_decay: 1e-4
  epoch: 300
  random_seed: 3000
  image_size: 800x800 #rowsxcols
  classes: data/coco_classes.txt
  data_worker: 0
inference:
  top_k: 1000
  resized: False
model:
  model_path: None
  exp_path: /data/Expr/Projects/8_object_detection/detr/tmp
  is_finetune: False
cuda:
  using_cuda: True
  gpu_id: 0
